### ISSUE TITLE
ImportError: No module named 'yellowfin'

### ISSUE THREAD

**Issue by yt605155624** [ChenglongChen/tensorflow-DeepFM#14]
\

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    from DeepFM import DeepFM
  File "../DeepFM.py", line 15, in <module>
    from yellowfin import YFOptimizer
ImportError: No module named 'yellowfin'
你好,我用1.0版本的tensorflow报错这句话,把tf升级成最新版本还是有这个问题,不知道该怎么解决?

**Comment by plenari** [comment]
这个函数只有优化的时候才用的上，可以注释掉把？

**Comment by ChenglongChen** [comment]
可以注释掉这行 https://github.com/ChenglongChen/tensorflow-DeepFM/blob/b0391f009c364c132ac927d39652519a473e7271/DeepFM.py#L15

如果想使用 YellowFin，可以去 https://github.com/JianGoForIt/YellowFin clone 他们的代码。
