### ISSUE TITLE
No module named yellowfin

### ISSUE THREAD

**Issue by CanoeFZH** [ChenglongChen/tensorflow-DeepFM#3]
```
(tensorflow) ➜  example git:(master) ✗ python main.py
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    from DeepFM import DeepFM
  File "../DeepFM.py", line 15, in <module>
    from yellowfin import YFOptimizer
```

**Comment by ChenglongChen** [comment]
Please download it from [here](https://github.com/JianGoForIt/YellowFin), and put it in the appropriate directory.
